version: '3'

services:

    registry:
        container_name: registry
        image: registry:2
        volumes: 
            - "$PWD/registry:/var/lib/registry"
        restart: always
        ports: 
            - 2000:2000
    
    portainer:
        container_name: portainer
        image: portainer/portainer
        env_file: 
            - .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports: 
            - 9000:9000
        